config/routes.rb
Rails.application.routes.draw do

  get 'home' => 'home#index'

  get 'mint' => 'mint#index'
  get 'contract_address' => 'mint#contract_address'
  get 'staking_contract_address' => 'mint#staking_contract_address'
  get 'abi' => 'mint#abi'
  get 'whitelist_addresses' => 'mint#whitelist_addresses'

  get 'faq' => 'faq#index'

  get 'roadmap' => 'roadmap#index'

  resources :artists

  resources :paintings

  resources :nfts

  resources :user_nfts, only: [:index, :show]
  get 'get_user_nfts' => 'user_nfts#get_user_nfts'

  resources :settings, only: [:index]

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', passwords: 'users/passwords' }
  resources :users, only: [:index]#, :update, :destroy]

  get 'imprint' => 'imprint#index'
  get 'privacy_notice' => 'privacy_notice#index'
  get 'terms' => 'terms#index'

  get 'health_check', to: proc { [200, {}, ['success']] }

  root "home#index"

end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :paintings
  has_many :nfts

  validates :name, presence: true

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]
  before_action { @section = 'database' }

  before_action :authenticate_admin!, except: [:index, :show]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @artists = Artist.all.limit(50)
  end

  def show

  end

  def new
    @artist = Artist.new
  end

  def edit

  end

  def create
    @artist = Artist.new(artist_params)
    respond_to do |format|
      if @artist.save
        format.html { redirect_to artist_path(@artist), notice: t('flash.notice.creating_artist') }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to artist_path(@artist), notice: t('flash.notice.updating_artist') }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @artist.destroy
        format.html { redirect_to artists_path, notice: t('flash.notice.deleting_artist') }
        format.json { head :no_content }
      else
        format.html { redirect_to artists_path(artist: @artist), alert: t('flash.alert.deleting_artist') }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def artist_params
      params.require(:artist).permit(:name, :description, :image_link, :wiki_link)
    end

end

app/views/artists/_artist.html.haml
%article.no-padding
  .row.no-space
    .col.s5.center-align
      = link_to artist_path(artist) do
        %img.responsive{src: artist.image_link, style: 'max-height: 265px !important;'}
    .col.s7
      = link_to artist_path(artist) do
        .padding
          %p.bold.large-text= artist.name
          %p.s= artist.description.truncate(90)
          %p.m= artist.description.truncate(320)
          %p.l= artist.description.truncate(900)
    -# - if current_user.present? && current_user.admin?
    -#   = link_to edit_artist_path(artist), style: 'position: absolute; right: 5px;' do
    -#     %i edit
    -# - if artist.wiki_link.present?
    -#   = link_to artist.wiki_link, target: '_blank', style: 'position: absolute; right: 5px; bottom: 5px;' do
    -#     %i info_outline

app/views/artists/_form.html.haml
= form_for artist, html: { "data-turbo": "false" } do |f|
  .row
    .col.s12
      - if artist.errors.any?
        #error_explanation
          %ul
            - artist.errors.full_messages.each do |message|
              %li= message
  .row
    .col.s12
      .field.label.border{style: 'margin-bottom: 0px;'}
        = f.text_field :name
        = f.label :name
  .row.mt-0
    .col.s12
      .field.label.border{style: 'margin-bottom: 0px;'}
        = f.text_field :description
        = f.label :description
  .row.mt-0
    .col.s12
      .field.label.border{style: 'margin-bottom: 0px;'}
        = f.text_field :image_link
        = f.label :image_link
  .row.mt-0
    .col.s12
      .field.label.border{style: 'margin-bottom: 0px;'}
        = f.text_field :wiki_link
        = f.label :wiki_link
  .row.mt-0
    .col.s12.center-align
      %button.small-elevate{type: 'submit'}
        %i save
        %span= t('save')

app/views/artists/edit.html.haml
.artists
  .row
    .col.s12.center-align
      %h1.page-title= 'Edit Artist'

  .row
    .col.s12.center-align
      = render 'form', artist: @artist

app/views/artists/index.html.haml
- set_meta_tags description: meta_tag_description('Artists')
.artists
  .row
    .col.s12.center-align
      %h1.page-title= 'Artists'

  .row
    .col.s12.center-align
      - if @artists.any?
        .row
          - @artists.each do |artist|
            .col.s12
              = render artist
      - else
        %p No artists found...

  - if current_user.present? && current_user.admin?
    .row
      .col.s12.center-align
        = link_to new_artist_path do
          %i add_circle_outline

app/views/artists/new.html.haml
.artists
  .row
    .col.s12.center-align
      %h1.page-title= 'New Artist'

  .row
    .col.s12.center-align
      = render 'form', artist: @artist

app/views/artists/show.html.haml
%turbo-frame#database-view
  .artists{data: { controller: 'hide-back-arrows' }}
    .row
      .col.s12.center-align
        %h1.page-title= @artist.name
    .row
      .col.s12.center-align
        %img.responsive{src: @artist.image_link}
    .row.mt-0
      .col.s12
        .padding
          %p= @artist.description
    - if @artist.wiki_link.present?
      .row.mt-0
        .col.s12.center-align{style: 'margin-top: -10px;'}
          = link_to @artist.wiki_link, target: '_blank' do
            %button.round.large
              %span Read more on Wikipedia

    - paintings = @artist.paintings
    - if paintings.any?
      - paintings_count = paintings.count
      .row.mt-0
        .col.s12
          .padding
            %h2.page-title= "Painting#{paintings_count > 1 ? 's' : ''}"
      .row.mt-0
        - paintings.each do |painting|
          .col.s4.center-align{class: "#{paintings_count == 1 ? 's12' : ''} #{paintings_count == 2 ? 's6' : ''}"}
            = link_to painting_path(painting, page: params[:page]), onclick: 'window.scrollTo({top: 0});' do
              %img.responsive{src: painting.image_link, style: 'max-height: 265px !important;'}

    - if current_user.present? && current_user.admin?
      .edit-icon{style: 'position: absolute; right: 5px; top: 5px;'}
        = link_to edit_artist_path(@artist) do
          %i edit
      .delete-icon{style: 'position: absolute; right: 5px; top: 45px;'}
        = form_with url: artist_path(@artist), id: "delete-artist-form", method: :delete do |f|
          = link_to '#', data: { controller: 'submit-closest-form' } do
            %i delete

    -# back arrows
    - if params[:nft_id].present?
      = link_to nft_path(params[:nft_id], page: params[:page]), class: 'back-arrow back-arrow-top color-default' do
        %i keyboard_backspace
      = link_to nft_path(params[:nft_id], page: params[:page]), class: 'back-arrow color-default' do
        %i keyboard_backspace