config/routes.rb
Rails.application.routes.draw do

  get 'home' => 'home#index'

  get 'mint' => 'mint#index'
  get 'contract_address' => 'mint#contract_address'
  get 'staking_contract_address' => 'mint#staking_contract_address'
  get 'abi' => 'mint#abi'
  get 'whitelist_addresses' => 'mint#whitelist_addresses'

  get 'faq' => 'faq#index'

  get 'roadmap' => 'roadmap#index'

  resources :artists

  resources :paintings

  resources :nfts

  resources :user_nfts, only: [:index, :show]
  get 'get_user_nfts' => 'user_nfts#get_user_nfts'

  resources :settings, only: [:index]

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', passwords: 'users/passwords' }
  resources :users, only: [:index]#, :update, :destroy]

  get 'imprint' => 'imprint#index'
  get 'privacy_notice' => 'privacy_notice#index'
  get 'terms' => 'terms#index'

  get 'health_check', to: proc { [200, {}, ['success']] }

  root "home#index"

end

app/controllers/user_nfts_controller.rb
class UserNftsController < ApplicationController
  before_action { @section = 'mint' }

  skip_before_action :authenticate_user!, only: [:index, :show, :get_user_nfts]

  # GET /user_nfts
  def index
  end

  # GET /user_nfts/1
  def show
    nft = Nft.find(params[:id])
    render partial: "show", locals: {nft: nft}
  end

  # GET /get_user_nfts
  def get_user_nfts
    contractAddress = params[:contractAddress]
    contractAddress = ENV['CONTRACT_ADDRESS'] if contractAddress.nil?
    userAddress = params[:userAddress]
    return unless userAddress.present?
    holder = Holder.find_or_create_by(wallet_address: userAddress)
    userNfts = holder.nfts(contractAddress) # this makes a alchemy_get_NFTs() request
    holder.last_time_seen = DateTime.now
    holder.save(touch: false)
    respond_to do |format|
      format.html { render partial: "user_nfts", locals: {userNfts: userNfts} }
      format.json { render json: userNfts.as_json(only: [:gif_link, :ipfs_token_id]) }
    end
  end

end

app/views/user_nfts/_show.html.haml
= turbo_frame_tag nft do
  .user-nfts
    .row
      .col.s12.center-align
        %h1.page-title= nft.name.gsub('vs.', '&')
    .row.mt-0.s
      .col.s6.center-align
        = link_to nft.artist, 'data-turbo-frame': '_top' do
          %img.responsive{src: nft.artist.image_link, style: 'max-height: 200px !important;'}
          .image-footer= 'Artist'
      .col.s6.center-align
        = link_to nft.painting, 'data-turbo-frame': '_top' do
          %img.responsive{src: nft.painting.image_link, style: 'max-height: 200px !important;'}
          .image-footer= 'Painting'
    .row{style: 'display: flex;'}
      .col.m.m4.l.center-align.middle-align
        = link_to nft.artist, 'data-turbo-frame': '_top' do
          %img.responsive{src: nft.artist.image_link, style: 'max-height: 200px !important;'}
          .image-footer= 'Artist'
      .col.s12.m3.center-align.middle-align
        = link_to nft, 'data-turbo-frame': '_top' do
          %img{src: nft.image_link, style: 'max-height: 200px !important;'}
          .image-footer= 'NFT'
      .col.m.m4.l.center-align.middle-align
        = link_to nft.painting, 'data-turbo-frame': '_top' do
          %img.responsive{src: nft.painting.image_link, style: 'max-height: 200px !important;'}
          .image-footer= 'Painting'
    .row.mt-0
      .col.s12
        .padding
          %p= nft.description
    .row.mt-0
      .col.s12.center-align.middle-align
        %h2.subtitle Traits
    = render partial: '/nfts/traits', locals: {nft: nft}

app/views/user_nfts/_user_nfts.html.haml
%turbo-frame#user-nfts-frame
  .user-nfts
    .row
      .col.s12.center-align
        %h1.page-title= 'My Dead Artists NFTs'

    = render partial: "/wallet/connect_button"

    .row
      - if userNfts.any?
        - userNfts_count = userNfts.count
        #user-nfts-data{data: {ctr: userNfts_count, ids: userNfts.map{|nft| nft.ipfs_token_id}}}
        - userNfts.each do |nft|
          .col.s6.m4.center-align{class: "#{userNfts_count == 1 ? 's12 m12' : ''} #{userNfts_count == 2 ? 's6 m6' : ''}"}
            .row
              .col.s12.center-align
                = link_to user_nft_path(nft), data: { turbo_frame: "nft_#{nft.id}" }, onclick: "ui('#user-nft-modal-#{nft.id}');" do
                  %img.responsive{src: nft.image_link, width: '265px', style: 'max-height: 265px !important;'}

                .modal{id: "user-nft-modal-#{nft.id}", style: 'border-radius: 12rem;'}
                  .modal-content{style: 'position: relative;'}
                    = turbo_frame_tag nft
            .row.mt-0
              .col.s12.center-align.mt-0
                %p.mt-0 Download links:
                .download-link.color-default
                  = link_to nft.gif_link, target: '_blank', download: "#{nft.name}_720x720" do
                    %span GIF: 720x720
                .download-link.color-default
                  = link_to nft.gif_link_no_id, target: '_blank', download: "#{nft.name}_no-ID_720x720" do
                    %span GIF: 720x720 (no ID)
                .download-link.color-default
                  = link_to nft.image_link, target: '_blank', download: "#{nft.name}_1080x1080" do
                    %span PNG: 1080x1080
                .download-link.color-default
                  = link_to nft.image_link_low_quali, target: '_blank', download: "#{nft.name}_720x720" do
                    %span JPG: 720x720
                .download-link.color-default
                  = link_to nft.collectible_link, target: '_blank', download: "#{nft.name}_collectible" do
                    %span Collectible (JPG)
                .download-link.color-default
                  = link_to nft.opensea_permalink, target: '_blank' do
                    %span Opensea permalink
                .download-link.color-default
                  = link_to nft.ipfs_token_uri, target: '_blank' do
                    %span IPFS token link
                .download-link.color-default
                  = link_to nft.ipfs_image_uri, target: '_blank' do
                    %span IPFS image link
                .download-link.color-default
                  %span= "Color code: #{nft.color_code}"

      - else
        .col.s12.center-align
          %p No NFTs found...

app/views/user_nfts/index.html.haml
%turbo-frame#user-nfts-frame{data: { controller: 'user-nfts' }}
  .user-nfts
    .row
      .col.s12.center-align
        %h1.page-title= 'My Dead Artists NFTs'

    = render partial: "/wallet/connect_button"

    .row
      .col.s12.center-align
        %p You must connect your wallet and own a DeadArtists NFT to see this page