config/routes.rb
Rails.application.routes.draw do

  get 'home' => 'home#index'

  get 'mint' => 'mint#index'
  get 'contract_address' => 'mint#contract_address'
  get 'staking_contract_address' => 'mint#staking_contract_address'
  get 'abi' => 'mint#abi'
  get 'whitelist_addresses' => 'mint#whitelist_addresses'

  get 'faq' => 'faq#index'

  get 'roadmap' => 'roadmap#index'

  resources :artists

  resources :paintings

  resources :nfts

  resources :user_nfts, only: [:index, :show]
  get 'get_user_nfts' => 'user_nfts#get_user_nfts'

  resources :settings, only: [:index]

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', passwords: 'users/passwords' }
  resources :users, only: [:index]#, :update, :destroy]

  get 'imprint' => 'imprint#index'
  get 'privacy_notice' => 'privacy_notice#index'
  get 'terms' => 'terms#index'

  get 'health_check', to: proc { [200, {}, ['success']] }

  root "home#index"

end

app/models/painting.rb
class Painting < ApplicationRecord
  belongs_to :artist
  has_one :nft

  validates :name, presence: true

end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  before_action :set_painting, only: [:show, :edit, :update, :destroy]
  before_action { @section = 'database' }

  before_action :authenticate_admin!, except: [:index, :show]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @artists = Artist.all.select(:id, :name)
    @paintings = Painting.includes(:artist).all.limit(50)
    @paintings = @paintings.where(artist_id: params[:artist_id]) if params[:artist_id].present?
  end

  def show

  end

  def new
    @painting = Painting.new
  end

  def edit

  end

  def create
    @painting = Painting.new(painting_params)
    respond_to do |format|
      if @painting.save
        format.html { redirect_to painting_path(@painting), notice: t('flash.notice.creating_painting') }
        format.json { render :show, status: :created, location: @painting }
      else
        format.html { render :new }
        format.json { render json: @painting.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @painting.update(painting_params)
        format.html { redirect_to painting_path(@painting), notice: t('flash.notice.updating_painting') }
        format.json { render :show, status: :ok, location: @painting }
      else
        format.html { render :edit }
        format.json { render json: @painting.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @painting.destroy
        format.html { redirect_to paintings_path, notice: t('flash.notice.deleting_painting') }
        format.json { head :no_content }
      else
        format.html { redirect_to paintings_path(painting: @painting), alert: t('flash.alert.deleting_painting') }
        format.json { render json: @painting.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_painting
      @painting = Painting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def painting_params
      params.require(:painting).permit(:name, :description, :image_link, :wiki_link, :artist_id)
    end

end

app/views/paintings/_form.html.haml
= form_for painting, html: { "data-turbo": "false" } do |f|
  .row
    .col.s12
      - if painting.errors.any?
        #error_explanation
          %ul
            - painting.errors.full_messages.each do |message|
              %li= message
  .row
    .col.s12
      .field.label.border{style: 'margin-bottom: 0px;'}
        = f.text_field :name
        = f.label :name
  .row.mt-0
    .col.s12
      .field.label.border{style: 'margin-bottom: 0px;'}
        = f.text_field :description
        = f.label :description
  .row.mt-0
    .col.s12
      .field.label.border{style: 'margin-bottom: 0px;'}
        = f.text_field :image_link
        = f.label :image_link
  .row.mt-0
    .col.s12
      .field.label.border{style: 'margin-bottom: 0px;'}
        = f.text_field :wiki_link
        = f.label :wiki_link
  .row.mt-0
    .col.s12
      .field.label.border{style: 'margin-bottom: 0px;'}
        = f.select :artist_id, Artist.all.collect {|a| [ a.name, a.id ] }, {include_blank: ''}
        = f.label :artist_id, 'Artist'
  .row.mt-0
    .col.s12.center-align
      %button.small-elevate{type: 'submit'}
        %i save
        %span= t('save')

app/views/paintings/_painting.html.haml
%article.no-padding
  .row.no-space
    .col.s5.center-align
      = link_to painting_path(painting) do
        %img.responsive{src: painting.image_link, style: 'max-height: 265px !important;'}
    .col.s7
      .row.no-space
        .col.s12.center-align
          %p.bold.large-text= painting.name
          -# %p.s= painting.description.truncate(90)
          -# %p.m= painting.description.truncate(320)
          -# %p.l= painting.description.truncate(900)
      .row
        .col.s12.center-align
          Artist
          .color-default
            = link_to artist_path(painting.artist) do
              %span.s= painting.artist.name.truncate(20)
              %span.m= painting.artist.name.truncate(30)
              %span.l= painting.artist.name.truncate(60)
    -# - if current_user.present? && current_user.admin?
    -#   = link_to edit_painting_path(painting), style: 'position: absolute; right: 5px;' do
    -#     %i edit
    -# - if painting.wiki_link.present?
    -#   = link_to painting.wiki_link, target: '_blank', style: 'position: absolute; right: 5px; bottom: 5px;' do
    -#     %i info_outline

app/views/paintings/edit.html.haml
.paintings
  .row
    .col.s12.center-align
      %h1.page-title= 'Edit Painting'

  .row
    .col.s12.center-align
      = render 'form', painting: @painting

app/views/paintings/index.html.haml
- set_meta_tags description: meta_tag_description('Paintings')
.paintings
  .row
    .col.s12.center-align
      %h1.page-title= 'Database'

  .row
    .col.s12.center-align
      - if @paintings.any?
        .row
          - @paintings.each do |painting|
            .col.s12.m6
              = render painting
      - else
        %p No paintings found...

  - if current_user.present? && current_user.admin?
    .row
      .col.s12.center-align
        = link_to new_painting_path do
          %i add_circle_outline

app/views/paintings/new.html.haml
.paintings
  .row
    .col.s12.center-align
      %h1.page-title= 'New Painting'

  .row
    .col.s12.center-align
      = render 'form', painting: @painting

app/views/paintings/show.html.haml
%turbo-frame#database-view
  .paintings{data: { controller: 'hide-back-arrows' }}
    .row
      .col.s12.center-align
        %h1.page-title= @painting.name
    .row
      .col.s12.center-align
        %img.responsive{src: @painting.image_link}
    .row.mt-0
      .col.s12
        .padding
          %p= @painting.description
    - if @painting.wiki_link.present?
      .row.mt-0
        .col.s12.center-align
          = link_to @painting.wiki_link, target: '_blank' do
            %button.round.large
              %span Read more on Wikipedia

    - artist = @painting.artist
    - nft = @painting.nft
    - if artist.present? || nft.present?
      .row.mt-0
        - if artist.present?
          .col.s6
            .row.no-space.mt-0
              .col.s12.center-align
                .padding
                  %h2.page-title= "Artist"
            .row.no-space.mt-0
              .col.s12.center-align
                - if artist.image_link.present?
                  = link_to artist_path(artist, nft_id: nft&.id, page: params[:page]), onclick: 'window.scrollTo({top: 0});' do
                    %img.responsive{src: artist.image_link, style: 'max-height: 200px !important;'}
                - else
                  = link_to artist.name, artist_path(artist, nft_id: nft&.id, page: params[:page]), class: 'color-default', onclick: 'window.scrollTo({top: 0});'
        - if nft.present?
          .col.s6
            .row.no-space.mt-0
              .col.s12.center-align
                .padding
                  %h2.page-title= "NFT"
            .row.no-space.mt-0
              .col.s12.center-align
                - if nft.image_link_low_quali.present?
                  = link_to nft_path(nft, page: params[:page]), onclick: 'window.scrollTo({top: 0});' do
                    %img.responsive{src: nft.image_link_low_quali, style: 'max-height: 200px !important;'}
                - else
                  = link_to nft.name, nft_path(nft, page: params[:page]), class: 'color-default', onclick: 'window.scrollTo({top: 0});'

    - if current_user.present? && current_user.admin?
      .edit-icon{style: 'position: absolute; right: 5px; top: 5px;'}
        = link_to edit_painting_path(@painting) do
          %i edit
      .delete-icon{style: 'position: absolute; right: 5px; top: 45px;'}
        = form_with url: painting_path(@painting), id: "delete-painting-form", method: :delete do |f|
          = link_to '#', data: { controller: 'submit-closest-form' } do
            %i delete

    -# back arrows
    - if nft.present?
      = link_to nft_path(nft, page: params[:page]), class: 'back-arrow back-arrow-top color-default' do
        %i keyboard_backspace
      = link_to nft_path(nft, page: params[:page]), class: 'back-arrow color-default' do
        %i keyboard_backspace