config/routes.rb
Rails.application.routes.draw do

  get 'home' => 'home#index'

  get 'mint' => 'mint#index'
  get 'contract_address' => 'mint#contract_address'
  get 'staking_contract_address' => 'mint#staking_contract_address'
  get 'abi' => 'mint#abi'
  get 'whitelist_addresses' => 'mint#whitelist_addresses'

  get 'faq' => 'faq#index'

  get 'roadmap' => 'roadmap#index'

  resources :artists

  resources :paintings

  resources :nfts

  resources :user_nfts, only: [:index, :show]
  get 'get_user_nfts' => 'user_nfts#get_user_nfts'

  resources :settings, only: [:index]

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', passwords: 'users/passwords' }
  resources :users, only: [:index]#, :update, :destroy]

  get 'imprint' => 'imprint#index'
  get 'privacy_notice' => 'privacy_notice#index'
  get 'terms' => 'terms#index'

  get 'health_check', to: proc { [200, {}, ['success']] }

  root "home#index"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action { @section = 'home' }

  skip_before_action :authenticate_user!, only: [:index]

  # GET /home
  def index
    demo_nft_ids = [5121, 2760, 4948, 4826, 5157, 4468, 3970]
    @demo_nft = Nft.find(demo_nft_ids.sample)
    unless @demo_nft.present?
      count = Rails.cache.fetch("nft_count", expires_in: 24.hours) do
        Nft.count
      end
      @demo_nft = Nft.offset(rand(count)).first
    end
  end

end

app/views/home/_text_band.html.haml
.text-band
  .zigzag.zigzag-top
  - if text.present?
    .marquee
      %span.text-band-text{style: "animation-duration: #{duration}"}
        = text
  .zigzag

app/views/home/index.html.haml
- set_meta_tags description: meta_tag_description('Home')
.home
  .row
    .col.s12.center-align
      %h1.page-title{style: 'display: none;'}= 'Dead Artists AI Home'
      = image_tag 'home_title.jpg', width: '100%', alt: 'Home title image'
  .row.mt-0
    .col.s12.center-align
      %p.m.l.home-text-subtitle{style: 'transform: rotate(-1deg);'}
        Yes, you should definitely own a famous dead artist like Van Gogh, Picasso or Da Vinci for yourself!
      %p.s.home-text-subtitle{style: 'transform: rotate(-1deg);'}
        Yes, you should definitely own a famous dead artist like Picasso or Da Vinci for yourself!

  .row
    .col.m.l.m4.center-align
      .artist-frame
        = video_tag 'vincent_van_gogh_neu3.webm', type: 'video/webm', controls: false, muted: true, loop: true, tabindex: "-1", autoplay: true
    .col.s6.m4.center-align
      .artist-frame
        = video_tag 'pablo_picasso_neu2.webm', type: 'video/webm', controls: false, muted: true, loop: true, tabindex: "-1", autoplay: true
    .col.s6.m4.center-align
      .artist-frame
        = video_tag 'leonardo_da_vinci_neu.webm', type: 'video/webm', controls: false, muted: true, loop: true, tabindex: "-1", autoplay: true

  .row
    .col.s12.center-align
      %p.home-text-paragraph
        Obtain a limited number of the 5000 animated artworks right here:
  .row
    .col.s12.center-align
      = link_to mint_path do
        %button.round.large
          %span= "Go to the <strong>Mint</strong> page".html_safe
          %i auto_awesome

  .row
    .col.s12.center-align
      = render 'text_band', duration: '20s', text: '5000 unique NFTs as GIFs • Over 250 different Artists • 20 different movement patterns • Unlockable content'

  .row.title-row#The-Art
    .col.s12.center-align
      %h2.page-title= 'The Art'
  .row.mt-0
    .col.s12.left-align
      %p.home-text-paragraph
        Each <span class='highlighted'>Dead Artists NFT</span> is based on a famous dead artist and one of his/her most famous paintings.
      %p.home-text-paragraph
        Since our rarity system originated from recent auction results, you can directly see the <span class='highlighted'>Dead Artists NFT</span> rarity as one of its NFT traits!
        %br
        Your <span class='highlighted'>Dead Artists NFT</span> comes with an unlockable "print out version" with a QR Code that links to its related <a href="https://www.opensea.io/" target="_blank" class="color-default">OpenSea</a> page.
  -# .row
  -#   .col.s12.center-align{style: 'margin-top: -10px;'}
  -#     = image_tag @demo_nft.gif_link_no_id, width: '300px', alt: 'NFT demo image'
  -#     -# = video_tag 'how_it_works.webm', type: 'video/webm', controls: false, muted: true, loop: false, tabindex: "-1", autoplay: false, id: 'how-it-works-video', onclick: "this.pause(); document.getElementById('play-svg').style.display = 'block';", width: '100%;'
  -#     -# = image_tag 'play.svg', id: 'play-svg', width: '50%', onclick: "this.style.display = 'none'; document.getElementById('how-it-works-video').play();", alt: 'how it works video play icon'
  .row.s
    .col.s6.center-align
      %a{style: 'cursor: default;'}
        %img.responsive{src: @demo_nft.artist.image_link, style: 'max-height: 200px !important;'}
          .image-footer= 'Artist'
    .col.s6.center-align
      %a{style: 'cursor: default;'}
        %img.responsive{src: @demo_nft.painting.image_link, style: 'max-height: 200px !important;'}
          .image-footer= 'Painting'
  .row{style: 'display: flex;'}
    .col.m.m4.l.center-align.middle-align
      %a{style: 'cursor: default;'}
        %img.responsive{src: @demo_nft.artist.image_link, style: 'max-height: 200px !important;'}
          .image-footer= 'Artist'
    .col.s12.m3.center-align.middle-align
      %a{style: 'cursor: default;'}
        %img.responsive{src: @demo_nft.gif_link_no_id, width: '265px', style: 'max-width: 265px !important; max-height: 265px !important;'}
          .image-footer= 'NFT'
    .col.m.m4.l.center-align.middle-align
      %a{style: 'cursor: default;'}
        %img.responsive{src: @demo_nft.painting.image_link, style: 'max-height: 200px !important;'}
          .image-footer= 'Painting'
  %br
  = render partial: '/nfts/traits', locals: {nft: @demo_nft}

  .row
    .col.s6.center-align
      .row.mt-0
        .col.s12.center-align
          = link_to faq_path do
            %button.border.round.large
              %span.m.l= "Go to the <strong>FAQs</strong> page".html_safe
              %span.s
                %strong FAQs
              %i live_help
    .col.s6.center-align
      .row.mt-0
        .col.s12.center-align
          = link_to roadmap_path do
            %button.border.round.large
              %span.m.l= "Go to the <strong>Roadmap</strong> page".html_safe
              %span.s
                %strong Roadmap
              %i map

  .row
    .col.s12.center-align
      = render 'text_band', duration: '39s', text: 'Claude Monet • Gustav Klimt • Edvard Munch • Pablo Picasso • Francis Bacon • Willem de Kooning • Vincent van Gogh • Andy Warhol • Leonora Carrington • Alla Horska • Cy Twombly • Leonardo da Vinci • Hilma af Klint • Wassily Kandinsky • Henri Matisse • Salvador Dali'

  .row.title-row#The-Art
    .col.s12.center-align
      %h2.page-title= 'The Utility'
  .row.mt-0
    .col.s12.left-align
      %p.home-text-paragraph
        <span class='highlighted'>Dead Artists NFT</span> collectors will be able to trade their NFT on trading platforms like <a href="https://rarible.com/" target="_blank" class="color-default">Rarible</a> and <a href="https://www.opensea.io/" target="_blank" class="color-default">OpenSea</a>.
      %p.home-text-paragraph
        If you don't want to sell your <span class='highlighted'>Dead Artists NFT</span>, you can just stake it to earn <span class='highlighted'>DAAI Coins</span>.
      %p.home-text-paragraph
        As soon as our shop is ready, you can use your <span class='highlighted'>DAAI Coins</span> to buy digital <span class='highlighted'>Dead Artists AI</span> merch.
        %br
        The shop will also containt physical <span class='highlighted'>Dead Artists AI</span> merch, that you can refine with images of the <span class='highlighted'>Dead Artists NFT</span> within your wallet.
      %p.home-text-paragraph.center-align
        Stay tuned!
  .row.mt-0
    .col.s12.center-align
      = image_tag 'shop_demo.jpg', width: '100%', id: 'shop-demo-image', alt: 'Shop demo image'

  .row.mt-0
    .col.s12.center-align
      = link_to roadmap_path do
        %button.border.round.large
          %span= "Go to the <strong>Roadmap</strong> page".html_safe
          %i map

  .row
    .col.s12.center-align
      = render 'text_band', text: nil

  .row.title-row#The-Community
    .col.s12.center-align
      %h2.page-title= 'The Community'
  .row.mt-0
    .col.s6.left-align
      %p.home-text-paragraph
        The Dead Artists community gets frequent project updates on Twitter and Discord.
      %p.home-text-paragraph.m.l
        We will give you a platform to talk about your favorite paintings, artists or NFTs.
      %p.home-text-paragraph.l
        Join our Discord and get in touch with the team.
    .col.s6.center-align
      = image_tag 'community_image.webp', width: '100%', style: 'max-width: 428px !important;', alt: 'Community image'
  .row.mt-0
    .col.m.m2.l.l3
    .col.s6.m4.l3.center-align
      = link_to 'https://twitter.com/DeadArtistsAI', target: '_blank', class: 'social-media-button' do
        = image_tag 'twitter_logo.webp', width: '150px', alt: 'twitter logo'
    .col.s6.m4.l3.center-align
      = link_to 'https://discord.gg/JN9Rhxmhgv', target: '_blank', class: 'social-media-button' do
        = image_tag 'discord_logo.webp', width: '150px', alt: 'discord logo'
    .col.m.m2.l.l3

  .row
    .col.s12.center-align
      = render 'text_band', text: nil

  .row.title-row#The-Dead-Artists-AI-Club
    .col.s12.center-align
      %h2.page-title= 'The Club'
  .row.mt-0
    .col.s6.m8.left-align
      %p.home-text-paragraph
        The <span class='highlighted'>Dead Artists NFT</span> is the key to an exclusive art club with many benefits.
      %p.home-text-paragraph
        Join the club by verifying yourself as a NFT collector in Discord.
      %p.home-text-paragraph
        You will be the first to get informed about cooperations and get whitelists from other interesting art related projects, exclusively selected by the <span class='highlighted'>Dead Artists AI</span> team.
    .col.s6.m4.center-align
      = image_tag 'club_image.webp', width: '100%', style: 'max-height: 361px !important; max-width: 241px !important;', alt: 'Club image'
      .row.s{style: 'margin-top: 20px;'}
        .col.s12.center-align
          = link_to 'https://discord.gg/JN9Rhxmhgv', target: '_blank', class: 'social-media-button' do
            = image_tag 'discord_logo.webp', alt: 'discord logo'

  .row
    .col.s12.center-align
      = render 'text_band', text: nil

  .row.title-row#The-Artist-Database
    .col.s12.center-align
      %h2.page-title= 'The Database'
  .row.mt-0{style: 'display: flex;'}
    .col.s8.m7.l8.left-align
      %p.home-text-paragraph
        In the database you can find all <span class='highlighted'>Dead Artists NFT</span> and their respective artist & painting they're are based on.
      %p.home-text-paragraph
        Use the search fields if you would like to find the NFT of your favorite artist or painting.
      %p.home-text-paragraph
      .row.m.l
        .col.s12.center-align{style: 'margin-top: 20px;'}
          = link_to nfts_path do
            %button.border.round.large
              %span= "Go to the <strong>Database</strong> page".html_safe
              %i filter
      .row.middle-align
        .col.s4.center-align
          = image_tag 'pablo_picasso2.webp', width: '100%', style: 'max-width: 202px !important;', alt: 'Pablo Picasso image beside his quote'
        .col.s8.left-align
          %p.home-text-paragraph{style: 'font-style: italic; font-family: playfair display,serif; letter-spacing: 0em;'}
            “Art washes away from the soul the dust of everyday life.”
            %br
            ― Pablo Picasso
    .col.s.s4.center-align.middle-align
      = image_tag 'artist_database_image_right_s.jpg', width: '100%', alt: 'Images of different artists within the database section'
    .col.m.m5.l.l4.center-align.middle-align{style: 'padding: 0; margin-left: -8rem;'}
      = image_tag 'artist_database_image_right.jpg', width: '100%', alt: 'Images of different artists within the database section'
  .row.mt-0.s
    .col.s12.center-align
      = link_to nfts_path do
        %button.border.round.large
          %span= "Go to the <strong>Database</strong> page".html_safe
          %i filter

  .row
    .col.s12.center-align
      = render 'text_band', text: nil

  .row.title-row#The-Team
    .col.s12.center-align
      %h2.page-title= 'The Team'
  .row.mt-0
    .col.s4.center-align
      = video_tag 'team_n.webm', type: 'video/webm', width: '100%', controls: false, muted: true, loop: true, tabindex: "-1", autoplay: true, class: 'team-member-video'
    .col.s4.center-align
      = video_tag 'team_l.webm', type: 'video/webm', width: '100%', controls: false, muted: true, loop: true, tabindex: "-1", autoplay: true, class: 'team-member-video'
    .col.s4.center-align
      = video_tag 'team_j.webm', type: 'video/webm', width: '100%', controls: false, muted: true, loop: true, tabindex: "-1", autoplay: true, class: 'team-member-video'
  .row.mt-0
    .col.s4.center-align{style: 'margin-top: -10px;'}
      %p.home-text-subtitle Loretta
      %p.home-text-paragraph "Art History Expert"
    .col.s4.center-align{style: 'margin-top: -10px;'}
      %p.home-text-subtitle Lucca
      %p.home-text-paragraph "AI Developer & Founder"
    .col.s4.center-align{style: 'margin-top: -10px;'}
      %p.home-text-subtitle Yomi
      %p.home-text-paragraph "Web Master"
  .row.mt-0
    .col.s4.center-align
      = video_tag 'team_b.webm', type: 'video/webm', width: '100%', controls: false, muted: true, loop: true, tabindex: "-1", autoplay: true, class: 'team-member-video'
  .row.mt-0
    .col.s4.center-align{style: 'margin-top: -10px;'}
      %p.home-text-subtitle Basti
      %p.home-text-paragraph "Community Manager"